### PR TITLE
Make the crate Windows compatible

### LINKED ISSUE #28: Failed to resolve: could not find `unix` in `os`
It looks like the crate  does not compile on Windows: https://github.com/soywod/himalaya/runs/5290902164?check_suite_focus=true. The issue comes from `use std::os::unix::fs::MetadataExt;`, which is obviously not available on Windows. Why not using `std::fs::Metadata`?

### PR DESCRIPTION
**Pull request by soywod**
Fixes #28.

I encountered many issues while developing this first draft. I let you know when it is ready for reviewing. I will also let comments to explain certain choices, so we can discuss about it.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -1,3 +1,8 @@
+#![cfg_attr(
+    all(target_os = "windows", feature = "nightly"),
+    feature(windows_by_handle)
+)]
```
Comment (soywod) [inline src/lib.rs]: I added those lines just to enable the `windows_by_handle` feature if we are on windows AND using the nightly rust toolchain, so we can use alternative functions for building random and unique ids.

File: src/lib.rs [hunk 2]
```diff
@@ -6,12 +11,20 @@ use std::fmt;
...
+use std::os::windows::fs::MetadataExt;
 use std::path::{Path, PathBuf};
 use std::time;
 
 use mailparse::*;
 
+#[cfg(unix)]
+const INFORMATIONAL_SUFFIX_SEPARATOR: &str = ":";
+#[cfg(windows)]
+const INFORMATIONAL_SUFFIX_SEPARATOR: &str = ";";
```
Comment (soywod) [inline src/lib.rs:21]: This is the biggest problem I encountered. Windows environments do not support the colon inside file names. I found nothing on the official doc, but I found this on [Wikipedia](https://en.wikipedia.org/wiki/Maildir#File-system_compatibility_issues):

> The Maildir standard can only be implemented on systems that accept colons in filenames.
>
> Systems that don't allow colons in filenames (this includes [Microsoft Windows](https://en.wikipedia.org/wiki/Microsoft_Windows) and some configurations of [Novell Storage Services](https://en.wikipedia.org/wiki/Novell_Storage_Services)) can use an alternative separator, such as ";" or "-". It is often trivial to patch [free and open-source software](https://en.wikipedia.org/wiki/Free_and_open-source_software) to use a different separator.

So I just tried a POC using a different separator and it seems to work. Now, the question is how to make this customizable? I thought about adding an entry in the `Maildir` struct (sth like `informational_suffix_separator`, or sth shorter like `info_suffix_delim`) with a default value set with the colon ":".

Let me know your opinion about this issue.

File: tests/smoke.rs [hunk 3]
```diff
@@ -25,9 +35,18 @@ where
...
+        let relative = relative.as_os_str();
+        #[cfg(windows)]
+        let relative = String::from_utf16(
+            relative
+                .as_os_str()
+                .encode_wide()
+                .collect::<Vec<_>>()
+                .as_slice(),
+        )
+        .unwrap();
```
Comment (soywod) [inline tests/smoke.rs]: All this bloc looks overwhelming, could not it be simpler to just do `relative.to_string_lossy().to_string().as_bytes()`?

File: tests/smoke.rs [hunk 4]
```diff
@@ -10,6 +13,13 @@ use walkdir::WalkDir;
 
 static TESTDATA_DIR: &str = "testdata";
 
+#[cfg(unix)]
+const MAILDIR_NAME: &str = "maildir-unix";
+#[cfg(windows)]
+const MAILDIR_NAME: &str = "maildir-windows";
```
Comment (soywod) [inline tests/smoke.rs]: Here I just copied the folder and renamed the file with the semicolon `;` separator.

**Comment by soywod** [comment]
I think the PR is ready for review. I still need your opinion on some comments I left. Let me know!

File: src/lib.rs (hunk 1 above)
Comment (staktrace) [reply src/lib.rs]: I'm opposed to having separate code for nightly vs release; it's really not necessary and adds complexity. If the code in the release branch is good enough to use, then it should be good enough for nightly too. It would be bad if the nightly-built code was incompatible or inconsistent with the release-built code (e.g. creating a maildir that can't be read). It would also be similarly bad if somewhere down the road we removed the nightly guard (because the feature is available in release) and then the behaviour of the software changes in an incompatible way. So I would prefer to strip out all the nightly stuff.

File: src/lib.rs (hunk 2 above)
Comment (staktrace) [reply src/lib.rs:21]: Hm, interesting. I hadn't considered this problem before. Using the semicolon is fine, and I'm ok with not making this customizable right now. It doesn't look like there's a standard around what windows maildir software uses so for now there's no clear "best option" but we can make it customizable later if there's a need for it.

File: tests/smoke.rs (hunk 4 above)
Comment (staktrace) [reply tests/smoke.rs]: I'd prefer to not duplicate test data. Can we instead just rename from ':' to ';' where appropriate when testing on Windows? Already the `with_maildir` function is copying the test data to a tmp dir for running the tests; after the percent-decoding step we can do a replacement of ':' to ';' and then use the modified name when copying to the tmp dir. Let me know if that doesn't make sense.

File: tests/smoke.rs (hunk 3 above)
Comment (staktrace) [reply tests/smoke.rs]: Really the pre-existing code here is wrong. We should never have to convert paths to strings (they should always be kept as OsStr/OsString). I'll do a separate PR to clean this up, that will simplify this part of your patch.

**Review by staktrace — CHANGES_REQUESTED** [review]
Thank you for the patch, and for pointing out all the pitfalls! I left a few comments below. In general I think given how under-specced maildir is on Windows we should probably go with the simplest possible approach that works. If we need to adjust it later for compatibility with other implementations it will be easier to do that.

**Comment by staktrace** [comment]
> I'll do a separate PR to clean this up, that will simplify this part of your patch.

Did this in https://github.com/staktrace/maildir/commit/547b53c14f8d530794aa25b26daa0c095d0a713b

File: src/lib.rs (hunk 1 above)
Comment (soywod) [reply src/lib.rs]: I understand, it makes sense. I will remove the guard!

File: src/lib.rs (hunk 2 above)
Comment (soywod) [reply src/lib.rs:21]: Alright, so we let this hunk as it is right now?

Comment (staktrace) [reply src/lib.rs:21]: Yes please!

File: src/lib.rs (hunk 1 above)
Comment (soywod) [reply src/lib.rs]: :heavy_check_mark:

File: tests/smoke.rs (hunk 3 above)
Comment (soywod) [reply tests/smoke.rs]: :heavy_check_mark:

File: tests/smoke.rs (hunk 4 above)
Comment (soywod) [reply tests/smoke.rs]: :heavy_check_mark:

**Comment by soywod** [comment]
The PR is ready for your second review.

**Comment by staktrace** [comment]
Thank you! The new changes look much better. I'll be squashing the patches together to clean up the history a bit, and I noticed a few minor cleanups that I'll throw in there as well. I should have this PR merged later today

**Comment by soywod** [comment]
Awesome! Like last time, could you please notify me when you release the new version? Because for now, windows builds are down for my tool, I need this patch to fix them. Thank you :pray:

**Comment by staktrace** [comment]
I updated the PR; there are now three commits. The changes are equivalent to what you had before; the slight changes I made were:
- avoid using * imports in `tests/smoke.rs`
- update a few code comments in `tests/smoke.rs`
- keep the "manual" rust install and cargo invocation in the `.github/workflows/test.yml` rather than using `actions-rs`. This is because using the action is (at present) an unnecessarily layer of abstraction that makes it harder to quickly understand what's happening and is also more verbose (requires extra `with` clauses).

**Comment by staktrace** [comment]
@soywod I've published it to crates.io as v0.6.1.
